alertmanager:
  config:
    receivers:
      - name: "null"  # Keep the default null receiver
      - name: "ntfy"  # Add your custom ntfy receiver
        webhook_configs:
          - send_resolved: true
            url: '{{ ntfy_custom_url }}'
    route:
      receiver: 'ntfy'
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
