alertmanager:
  tplConfig: false  # Disable Helm templating for Alertmanager config
  config:
    templates:
      - /etc/alertmanager/templates/ntfy-template.tmpl
    receivers:
      - name: "ntfy"
        webhook_configs:
          - send_resolved: true
            url: '{{ ntfy_custom_url }}'
            template: ntfy-template.tmpl
    route:
      receiver: 'ntfy'
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h