---
- name: Create manifests directory for gh-actions configuration
  file:
    path: /tmp/k3s/gh-actions
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0755
  run_once: true

- name: Ensure arc-runners namespace exists
  command: >
    k3s kubectl create namespace arc-runners
  args:
    creates: /tmp/k3s/arc-runners-created
  register: create_namespace_result_arc
  failed_when: create_namespace_result_arc.rc != 0 and "already exists" not in create_namespace_result_arc.stderr
  changed_when: create_namespace_result_arc.rc == 0
  run_once: true


- name: Create rbac resource for gh-actions
  template:
    src: "gh-actions-setup-template.yaml.j2"
    dest: "/tmp/k3s/gh-actions.yaml"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  run_once: true

- name: Apply gh-actions rbac resource
  command: >
    k3s kubectl apply -f /tmp/k3s/gh-actions.yaml
  register: gh_actions_apply_result
  changed_when: false
  run_once: true
  until: gh_actions_apply_result.rc == 0
  retries: 5